[build-system]
requires = ["scikit-build-core>=0.5.0", "nanobind>=2.0.0"]
build-backend = "scikit_build_core.build"

[project]
name = "moveitmoveit"
version = "1.0.0"
description = "High performance Python IPC work stealing deque"
readme = "README.md"
requires-python = ">=3.9"
authors = [
    { name = "David Meng", email = "davidmenggx@gmail.com" }
]
dependencies = []

[tool.scikit-build]
cmake.version = ">=3.18"
ninja.version = ">=1.10"

[tool.scikit-build.cmake.define]
BUILD_TESTING = "OFF"

