

class Abort(Exception):
    pass

class Empty(Exception):
    pass

class Deque:
    def __init__(self, group_id: str, total_memory_capacity_mb: int = 16384) -> None: ...

    def put(self, data: object) -> None: ...

    def try_put(self, data: object) -> None: ...

    def get(self) -> object: ...

    def steal(self, target_longest: bool = False, target_first: bool = False) -> object: ...

    def qsize(self) -> int: ...

    def empty(self) -> bool: ...

    def full(self) -> bool: ...
